// Notes 笔记本相关文案 SSOT.
//
// 覆盖: components/notes/* + views/NotesHome.tsx + views/NoteEditor.tsx
// 调性: §1.3 不打鸡血, 引导用户记录但不催。

export const NOTES_COPY = {
  // CaptureBar
  captureBarPlaceholder:  '写下此刻的想法',
  captureBarAriaLabel:    '快速捕获笔记内容',
  captureBarTypeAriaLabel: '笔记类型',
  captureDomainAriaLabel: '笔记产生学习域',
  // CommunityNotesSection
  communityEmpty:         '还没有同学的笔记',
  communityEmptyHint1:    '把你的解题思路记下来',
  communityEmptyHint2:    '别人也能看到',
  communityHeader:        '同学的笔记',
  // NoteCaptureLauncher
  launcherTooltip:        '添加到笔记',
  // NoteCaptureModal
  captureLinkXingce:      '关联行测题',
  captureLinkEssay:       '关联申论题',
  captureExample1:        '记下打动你的那一句',
  captureExample2:        '总结一种可复用的方法',
  captureExample3a:       '为什么这道题出错',
  captureExample3b:       '这次有什么启发',
  captureExample4:        '记录一段素材',
  captureModalTitle:      '添加到笔记',
  captureModalSubtitle1:  '记下这一刻的灵感',
  captureModalSubtitle2:  '关联当前题目自动',
  captureModalConfirm:    '添加到笔记',
  captureRetryHint:       '请稍后重试',
  // NoteCommentsList
  commentsEmpty:          '还没有评论',
  commentsPlaceholder:    '写一条评论',
  commentsAriaLabel:      '写一条评论',
  // NotesToolbar
  toolbarSearchPlaceholder: '搜索笔记标题',
  toolbarDomainAriaLabel:   '学习域筛选',
  toolbarSortByCreated:     '按创建时间',
  toolbarSortByUpdated:     '按更新时间',
  // ReviewStack
  reviewEmpty:            '暂无待复习卡片',
  reviewEmptyHint1:       '创建笔记后',
  reviewEmptyHint2:       '间隔重复推送复习队列',
  // SprintCard
  sprintTitle:            '考前冲刺池',
  sprintGoldQuotes:       '高频金句池',
  sprintMethodCards:      '方法论卡片',
  sprintDailySuggestion:  '建议每日复习',
  // views/NoteEditor
  editorEyebrow:          'Editor · 思考',
  editorNewTitle:         '新建笔记',
  editorEditTitle:        '编辑笔记',
  editorSubtitle:         '选择类型 + 来源，写下要点。跨领域单池，复习自动入队列。',
  editorRequireLogin:     '登录后即可编辑笔记',
  editorInvalidLinkTitle: '笔记链接无效',
  editorInvalidLinkDesc:  '可能已被删除或链接有误',
  editorBackToNotes:      '返回笔记本',
  editorBack:             '返回',
  editorLoadFailedTitle:  '笔记加载失败',
  editorLoadFailedDesc:   '检查网络后重试',
  editorRetry:            '重试',
  editorCreatedToast:     '笔记已创建',
  editorSavedToast:       '已保存',
  editorCreateFailedTitle: '创建失败',
  editorSaveFailedTitle:  '保存失败',
  editorRetryHint:        '检查网络后重试',
  editorPoolHint1:        '跨领域单池',
  editorPoolHint2:        '复习自动入队列',
  editorSaveNew:          '保存笔记',
  editorSaveEdit:         '保存修改',
  editorTitleLabel:       '标题',
  editorTitlePlaceholder: '给笔记起个名字',
  editorTypeLabel:        '类型',
  editorTypeQuote:        '金句',
  editorTypeMethod:       '方法论',
  editorTypeReflect:      '反思',
  editorTypeMaterial:     '素材',
  editorSourceDomainLabel: '学习域',
  editorSourceDomainEssay: '申论',
  editorSourceDomainXingce: '行测',
  editorSourceRefLabel:   '来源',
  editorSourceRefPlaceholder: '例如: 2023 国考副省 第三题',
  editorTagsLabel:        '标签 (逗号分隔)',
  editorTagsPlaceholder:  '#治理之细, #政策梳理',
  editorMethodTitleLabel: '方法标题',
  editorMethodTitlePlaceholder: '例: 归纳概括 · 三步法',
  editorMethodStepsLabel: '步骤 (每行一步, 格式: 序号|说明)',
  editorMethodStepsPlaceholder: '1|抓主体\n2|分维度\n3|整合表达',
  editorMaterialRowsLabel: '字段 (每行一条, 格式: 字段名|值)',
  editorMaterialRowsPlaceholder: '人物|周一同\n地点|江西省\n核心动作|主导政策梳理工程',
  editorBodyLabel:        '正文',
  editorQuotePlaceholder:  '记下精彩的论述或表达',
  editorReflectPlaceholder: '写下你的反思与思考',
  editorFooterCharCount:  '字数',
  editorFooterNoTags:     '尚无引用',
  editorFooterTagsCount: (count: number): string =>
    `引用 ${count} 个标签`,
  // views/NotesHome
  homeEyebrow:            'Notebook · 思考',
  homeTitle:              '笔记本',
  homeSubtitle:           '跨领域单池，行测 + 申论统一收录。复习走间隔重复算法，一日 5 张，跨域混合。',
  homeNewCta:             '新建笔记',
  homeRequireLogin:       '登录后即可查看你的笔记本',
  homeLoadFailedTitle:    '笔记本加载失败',
  homeLoadFailedDesc:     '检查网络后重试',
  homeRetry:              '重试',
  homeQuickCaptureSourceRef: '快速捕获',
  homeCreateSuccessTitle: '已添加',
  homeCreateFailedTitle:  '添加失败',
  homeReviewFailedTitle:  '评分失败',
  homeReviewRetry:        '检查网络后重试',
  homeCreatedHint:        '可在编辑器内继续完善',
  homeCreateRetry:        '检查网络后重试',
  homeDeleteRetry:        '检查网络后重试',
  homePoolHint1:          '跨领域单池',
  homePoolHint2:          '申论统一收录',
  homePoolHint3:          '复习走间隔重复算法',
  homeEmpty:              '还没有笔记',
  homeEmptyHint1:         '从顶部捕获条快速添加，',
  homeEmptyHint2:         '或新建笔记开始整理。',
  homeFilteredEmpty:      '没有符合筛选的笔记',
  homeFilteredEmptyHint:  '换个筛选条件试试。',
  homeLoadedAllCount:     (count: number): string => `已加载全部 · 共 ${count} 条`,
  homeSkipTitle:          '已跳过',
  homeReviewLater:        '稍后会再次出现',
  homeSprintToastTitle:   '冲刺池',
  homeReviewActive:       '内自动激活',
} as const;
