// Notes 笔记本相关文案 SSOT.
//
// 覆盖: components/notes/* + views/NotesHome.tsx + views/NoteEditor.tsx
// 调性: §1.3 不打鸡血, 引导用户记录但不催。

export const NOTES_COPY = {
  // CaptureBar
  captureBarPlaceholder:  '写下此刻的想法',
  captureBarAriaLabel:    '快速捕获笔记内容',
  captureDomainAriaLabel: '笔记产生学习域',
  // CommunityNotesSection
  communityEmpty:         '还没有同学的笔记',
  communityEmptyHint1:    '把你的解题思路记下来',
  communityEmptyHint2:    '别人也能看到',
  communityHeader:        '同学的笔记',
  // NoteCaptureLauncher
  launcherTooltip:        '添加到笔记',
  // NoteCaptureModal
  captureLinkXingce:      '关联行测题',
  captureLinkEssay:       '关联申论题',
  captureExample1:        '记下打动你的那一句',
  captureExample2:        '总结一种可复用的方法',
  captureExample3a:       '为什么这道题出错',
  captureExample3b:       '这次有什么启发',
  captureExample4:        '记录一段素材',
  captureModalTitle:      '添加到笔记',
  captureModalSubtitle1:  '记下这一刻的灵感',
  captureModalSubtitle2:  '关联当前题目自动',
  captureModalConfirm:    '添加到笔记',
  captureRetryHint:       '请稍后重试',
  // NoteCommentsList
  commentsEmpty:          '还没有评论',
  commentsPlaceholder:    '写一条评论',
  commentsAriaLabel:      '写一条评论',
  // NotesToolbar
  toolbarSearchPlaceholder: '搜索笔记标题',
  toolbarDomainAriaLabel:   '学习域筛选',
  toolbarSortByCreated:     '按创建时间',
  toolbarSortByUpdated:     '按更新时间',
  // ReviewStack
  reviewEmpty:            '暂无待复习卡片',
  reviewEmptyHint1:       '创建笔记后',
  reviewEmptyHint2:       '间隔重复推送复习队列',
  // SprintCard
  sprintTitle:            '考前冲刺池',
  sprintGoldQuotes:       '高频金句池',
  sprintMethodCards:      '方法论卡片',
  sprintDailySuggestion:  '建议每日复习',
  // views/NoteEditor
  editorRequireLogin:     '登录后即可编辑笔记',
  editorInvalidLinkTitle: '笔记链接无效',
  editorInvalidLinkDesc:  '可能已被删除或链接有误',
  editorBackToNotes:      '返回笔记本',
  editorLoadFailedTitle:  '笔记加载失败',
  editorLoadFailedDesc:   '检查网络后重试',
  editorCreatedToast:     '笔记已创建',
  editorRetryHint:        '检查网络后重试',
  editorPoolHint1:        '跨领域单池',
  editorPoolHint2:        '复习自动入队列',
  editorTitlePlaceholder: '给笔记起个名字',
  editorDomainPlaceholder: '主导政策梳理工程',
  editorQuotePlaceholder:  '记下精彩的论述或表达',
  editorReflectPlaceholder: '写下你的反思与思考',
  // views/NotesHome
  homeRequireLogin:       '登录后即可查看你的笔记本',
  homeLoadFailedTitle:    '笔记本加载失败',
  homeLoadFailedDesc:     '检查网络后重试',
  homeCreatedHint:        '可在编辑器内继续完善',
  homeCreateRetry:        '检查网络后重试',
  homeDeleteRetry:        '检查网络后重试',
  homePoolHint1:          '跨领域单池',
  homePoolHint2:          '申论统一收录',
  homePoolHint3:          '复习走间隔重复算法',
  homeEmpty:              '还没有笔记',
  homeEmptyHint1:         '从顶部捕获条快速添加',
  homeEmptyHint2:         '或新建笔记开始整理',
  homeFilteredEmpty:      '没有符合筛选的笔记',
  homeFilteredEmptyHint:  '换个筛选条件试试',
  homeLoadedAll:          '已加载全部',
  homeReviewLater:        '稍后会再次出现',
  homeReviewActive:       '内自动激活',
} as const;
