// Profile view copy SSOT.
//
// Covers: views/Profile.tsx + components/profile/*

export const PROFILE_COPY = {
  studyToolsHeader: '学习与工具',
  studyToolsSubtitle: '完整数据和历史记录收进独立页面，个人中心只保留常用入口。',
  analyticsLabel: '学情数据',
  rowAnalyticsSubtitle: '查看累计练习、正确率和错题沉淀',
  planLabel: '学习计划',
  rowPlanSubtitle: '回看历史计划和阶段安排',
  essayLabel: '我的申论',
  rowEssaySubtitle: '查看申论批改和示范答案',
  conversationsLabel: '解析问答',
  rowConversationsSubtitle: '查看过去的问答记录',
  anonymousDisplayName: '匿名',
  guestHandle: 'guest',
  memberSincePrefix: '加入于',
  statStreakLabel: '连续打卡',
  statHoursLabel: '累计时长',
  statAnsweredLabel: '累计题量',
  statWrongLabel: '错题',
  statMembershipLabel: '当前会员',
  basicInfoEyebrow: 'ACCOUNT',
  basicInfoTitle: '基本资料',
  basicInfoNameLabel: '姓名',
  basicInfoPhoneLabel: '手机',
  basicInfoEmailLabel: '邮箱',
  basicInfoTargetLabel: '目标考试',
  basicInfoRegionLabel: '报考地区',
  basicInfoEditAction: '编辑',
  basicInfoChangeAction: '更换',
  securityTitle: '账户安全',
  securityEmailFallback: '邮箱',
  securityPhoneFallback: '手机号',
  securityBoundSubtitle: '已绑定',
  securityUnboundSubtitle: '尚未绑定',
  securityBindEmailCta: '绑定邮箱',
  securityBindPhoneCta: '绑定手机',
  securityPasswordTitle: '修改密码',
  securityPasswordSubtitle: '改密功能即将上线',
  emailPanelTitle: '邮箱',
  emailPanelEmpty: '尚未绑定邮箱',
  emailPanelBindAction: '绑定邮箱',
  emailPanelChangeAction: '更换邮箱',
  preferencesTitle: '偏好',
  preferencesThemeLabel: '主题',
  preferencesThemeQuiet: '静读',
  preferencesThemePure: '素白',
  preferencesThemeNight: '夜读',
  preferencesThemeHint: '在 Tweaks 中切换',
  preferencesReminderLabel: '每日提醒',
  preferencesReminderEmpty: '未设置',
  preferencesFontLabel: '字号',
  preferencesFontDefault: '中 · 15 px',
  preferencesShortcutsLabel: '键盘快捷键',
  preferencesShortcutsEnabled: '已开启 · ⌘K · ⌘/',
  preferencesShortcutsDisabled: '已关闭',
  subscriptionTitle: '订阅',
  subscriptionTierPremium: 'PREMIUM',
  subscriptionBillingMonthly: '月度订阅',
  subscriptionDefaultPerks: ['完整真题库', '申论批改', 'AI 解析', '学习计划生成'] as const,
  subscriptionPriceLabel: '¥38',
  subscriptionPriceCycle: '月',
  subscriptionEmptyRenewDate: '尚未订阅',
  subscriptionManageAction: '管理订阅',
  logoutAction: '退出登录',
} as const;
