/*
 * MSW browser worker — DEV-only entry (SIK-89 Home M-Auth, 2026-05-24).
 *
 * Why: this module is imported only behind `import.meta.env.DEV` in
 *      apps/web/src/main.tsx so vite tree-shakes it out of prod bundles.
 *      Acceptance gate: `npm run build` followed by grep on dist/ must
 *      not surface 'msw' / 'setupWorker' / 'service-worker' references.
 *
 *      The service worker file `mockServiceWorker.js` is generated by
 *      `npx msw init apps/web/public --save` once per repo (committed to
 *      git). Re-run only if msw bumps a major and changes the worker
 *      script payload.
 */
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
