/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v2_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v2_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/register/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Email */
        post: operations["register_email_api_v2_auth_register_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/register/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Phone */
        post: operations["register_phone_api_v2_auth_register_phone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v2_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Code */
        post: operations["send_code_api_v2_auth_send_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v2_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Code */
        post: operations["verify_code_api_v2_auth_verify_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Overview */
        get: operations["get_dashboard_overview_api_v2_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Overview */
        get: operations["get_progress_overview_api_v2_dashboard_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/progress/diagnosis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Diagnosis */
        get: operations["get_progress_diagnosis_api_v2_dashboard_progress_diagnosis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/progress/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Trend */
        get: operations["get_progress_trend_api_v2_dashboard_progress_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/progress/weakness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Weakness */
        get: operations["get_progress_weakness_api_v2_dashboard_progress_weakness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Records */
        get: operations["get_dashboard_records_api_v2_dashboard_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Today */
        get: operations["get_dashboard_today_api_v2_dashboard_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/today/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Today Continue */
        get: operations["get_dashboard_today_continue_api_v2_dashboard_today_continue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/today/must-do": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Today Must Do */
        get: operations["get_dashboard_today_must_do_api_v2_dashboard_today_must_do_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/today/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Today Review */
        get: operations["get_dashboard_today_review_api_v2_dashboard_today_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/weekly-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Weekly Plan */
        get: operations["get_dashboard_weekly_plan_api_v2_dashboard_weekly_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/weekly-plan/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Weekly Adjust */
        get: operations["get_dashboard_weekly_adjust_api_v2_dashboard_weekly_plan_adjust_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/weekly-plan/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Weekly Goal */
        get: operations["get_dashboard_weekly_goal_api_v2_dashboard_weekly_plan_goal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/weekly-plan/today-completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Weekly Completion */
        get: operations["get_dashboard_weekly_completion_api_v2_dashboard_weekly_plan_today_completion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_v2_notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_api_v2_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Note */
        get: operations["get_note_api_v2_notes__note_id__get"];
        /** Update Note */
        put: operations["update_note_api_v2_notes__note_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/center": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Center */
        get: operations["get_practice_center_api_v2_practice_center_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/essay/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Essay Categories */
        get: operations["list_essay_categories_api_v2_practice_essay_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/essay/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Essay Papers */
        get: operations["list_essay_papers_api_v2_practice_essay_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v2_practice_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v2_practice_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/sessions/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Answers */
        post: operations["save_answers_api_v2_practice_sessions__session_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/sessions/{session_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_v2_practice_sessions__session_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/sessions/{session_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Session */
        post: operations["submit_session_api_v2_practice_sessions__session_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/xingce/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Xingce Categories */
        get: operations["list_xingce_categories_api_v2_practice_xingce_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/practice/xingce/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Xingce Papers */
        get: operations["list_xingce_papers_api_v2_practice_xingce_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/profile/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Goals */
        get: operations["get_profile_goals_api_v2_profile_goals_get"];
        /** Put Profile Goals */
        put: operations["put_profile_goals_api_v2_profile_goals_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/profile/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Info */
        get: operations["get_profile_info_api_v2_profile_info_get"];
        /** Put Profile Info */
        put: operations["put_profile_info_api_v2_profile_info_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/profile/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Overview */
        get: operations["get_profile_overview_api_v2_profile_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/profile/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Security */
        get: operations["get_profile_security_api_v2_profile_security_get"];
        /** Put Profile Security */
        put: operations["put_profile_security_api_v2_profile_security_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Review Items */
        get: operations["list_review_items_api_v2_review_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Item */
        get: operations["get_review_item_api_v2_review_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/items/{item_id}/redo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redo Review Item */
        post: operations["redo_review_item_api_v2_review_items__item_id__redo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/review/smart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Smart Review */
        get: operations["get_smart_review_api_v2_review_smart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/system/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_v2_system_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Json */
        get: operations["version_json_version_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionLinkV2 */
        ActionLinkV2: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Href */
            href: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** AuthAckV2 */
        AuthAckV2: {
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /** AuthSessionResponseV2 */
        AuthSessionResponseV2: {
            session: components["schemas"]["AuthSessionV2"];
            user: components["schemas"]["AuthUserV2"];
        };
        /** AuthSessionStateResponseV2 */
        AuthSessionStateResponseV2: {
            /** Authenticated */
            authenticated: boolean;
            session: components["schemas"]["AuthSessionV2"];
            user: components["schemas"]["AuthUserV2"];
        };
        /** AuthSessionV2 */
        AuthSessionV2: {
            /** Expiresat */
            expiresAt: string;
            /** Id */
            id: number;
            /** Issuedat */
            issuedAt: string;
        };
        /** AuthUserV2 */
        AuthUserV2: {
            /** Createdat */
            createdAt: string;
            /** Displayname */
            displayName: string;
            /** Email */
            email?: string | null;
            /** Id */
            id: number;
            /** Isactive */
            isActive: boolean;
            /** Phone */
            phone?: string | null;
            /** Publicid */
            publicId: string;
        };
        /** BootstrapResponseV2 */
        BootstrapResponseV2: {
            /** Appname */
            appName: string;
            /** Canstartpractice */
            canStartPractice: boolean;
            /** Defaultpapercode */
            defaultPaperCode?: string | null;
            /** Env */
            env: string;
            /** Publishedpapercount */
            publishedPaperCount: number;
        };
        /** CatalogItemV2 */
        CatalogItemV2: {
            /** Href */
            href: string;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
        };
        /** CatalogListResponseV2 */
        CatalogListResponseV2: {
            /** Items */
            items: components["schemas"]["CatalogItemV2"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** DashboardProgressResponseV2 */
        DashboardProgressResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            /** Summary */
            summary: components["schemas"]["SummaryMetricV2"][];
        };
        /** DashboardRecordsResponseV2 */
        DashboardRecordsResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Items */
            items: components["schemas"]["LearningRecordItemV2"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            summary: components["schemas"]["LearningRecordSummaryV2"];
            /** Total */
            total: number;
        };
        /** DashboardTodayResponseV2 */
        DashboardTodayResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            /** Summary */
            summary: components["schemas"]["SummaryMetricV2"][];
        };
        /** DashboardWeeklyPlanResponseV2 */
        DashboardWeeklyPlanResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            /** Summary */
            summary: components["schemas"]["SummaryMetricV2"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LearningRecordItemV2 */
        LearningRecordItemV2: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Occurredat */
            occurredAt: string;
            /** Score */
            score?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** LearningRecordSummaryV2 */
        LearningRecordSummaryV2: {
            /** Avgessayscore */
            avgEssayScore?: string | null;
            /** Avgxingceaccuracy */
            avgXingceAccuracy?: string | null;
            /** Completedattempts */
            completedAttempts: number;
            /** Essayattempts */
            essayAttempts: number;
            /** Totalattempts */
            totalAttempts: number;
            /** Xingceattempts */
            xingceAttempts: number;
        };
        /** LoginRequestV2 */
        LoginRequestV2: {
            /** Identifier */
            identifier: string;
            /** Password */
            password: string;
        };
        /** NoteCreateRequestV2 */
        NoteCreateRequestV2: {
            /**
             * Body
             * @default
             */
            body: string;
            /** Title */
            title: string;
        };
        /** NoteDetailV2 */
        NoteDetailV2: {
            /** Body */
            body: string;
            /** Createdat */
            createdAt: string;
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Updatedat */
            updatedAt: string;
        };
        /** NoteItemV2 */
        NoteItemV2: {
            /** Createdat */
            createdAt: string;
            /** Excerpt */
            excerpt: string;
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Updatedat */
            updatedAt: string;
        };
        /** NoteListResponseV2 */
        NoteListResponseV2: {
            /** Items */
            items: components["schemas"]["NoteItemV2"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** NoteUpdateRequestV2 */
        NoteUpdateRequestV2: {
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Title */
            title: string;
        };
        /** OperationAckV2 */
        OperationAckV2: {
            /** Ok */
            ok: boolean;
            /** Status */
            status: string;
        };
        /** OverviewResponseV2 */
        OverviewResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            /** Summary */
            summary: components["schemas"]["SummaryMetricV2"][];
        };
        /** PracticeAnswerPayloadV2 */
        PracticeAnswerPayloadV2: {
            /** Answer */
            answer?: {
                [key: string]: unknown;
            };
            /** Durationseconds */
            durationSeconds?: number | null;
            /** Questionkey */
            questionKey: string;
        };
        /** PracticeAnswerUpsertRequestV2 */
        PracticeAnswerUpsertRequestV2: {
            /** Answers */
            answers?: components["schemas"]["PracticeAnswerPayloadV2"][];
        };
        /** PracticeCenterResponseV2 */
        PracticeCenterResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            /** Summary */
            summary: components["schemas"]["SummaryMetricV2"][];
        };
        /** PracticeSessionCreateRequestV2 */
        PracticeSessionCreateRequestV2: {
            /** Entrykind */
            entryKind: string;
            /** Papercode */
            paperCode?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Questionids */
            questionIds?: number[];
            /**
             * Track
             * @enum {string}
             */
            track: "xingce" | "essay";
        };
        /** PracticeSessionEnvelopeV2 */
        PracticeSessionEnvelopeV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Entrykind */
            entryKind: string;
            /** Id */
            id: number;
            /** Items */
            items: components["schemas"]["PracticeSessionItemV2"][];
            /** Startedat */
            startedAt: string;
            /** Status */
            status: string;
            /** Submittedat */
            submittedAt?: string | null;
            /** Track */
            track: string;
        };
        /** PracticeSessionItemV2 */
        PracticeSessionItemV2: {
            /** Answerkind */
            answerKind: string;
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /** Questionkey */
            questionKey?: string | null;
            /** Status */
            status: string;
        };
        /** PracticeSessionResultResponseV2 */
        PracticeSessionResultResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            /** Summary */
            summary: components["schemas"]["SummaryMetricV2"][];
        };
        /** ProfileGoalsResponseV2 */
        ProfileGoalsResponseV2: {
            /** Targetexam */
            targetExam?: string | null;
            /** Targetscore */
            targetScore?: string | null;
            /** Weeklytargethours */
            weeklyTargetHours?: number | null;
        };
        /** ProfileGoalsUpdateRequestV2 */
        ProfileGoalsUpdateRequestV2: {
            /** Targetexam */
            targetExam?: string | null;
            /** Targetscore */
            targetScore?: number | string | null;
            /** Weeklytargethours */
            weeklyTargetHours?: number | null;
        };
        /** ProfileInfoResponseV2 */
        ProfileInfoResponseV2: {
            /** Bio */
            bio?: string | null;
            /** Displayname */
            displayName: string;
            /** Realname */
            realName?: string | null;
            /** Region */
            region?: string | null;
        };
        /** ProfileInfoUpdateRequestV2 */
        ProfileInfoUpdateRequestV2: {
            /** Bio */
            bio?: string | null;
            /** Displayname */
            displayName: string;
            /** Realname */
            realName?: string | null;
            /** Region */
            region?: string | null;
        };
        /** ProfileOverviewResponseV2 */
        ProfileOverviewResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** Sections */
            sections: components["schemas"]["SectionCardV2"][];
            /** Summary */
            summary: components["schemas"]["SummaryMetricV2"][];
        };
        /** ProfileSecurityResponseV2 */
        ProfileSecurityResponseV2: {
            /** Activesessions */
            activeSessions: number;
            /** Emailbound */
            emailBound: boolean;
            /** Passwordset */
            passwordSet: boolean;
            /** Phonebound */
            phoneBound: boolean;
        };
        /** ProfileSecurityUpdateRequestV2 */
        ProfileSecurityUpdateRequestV2: {
            /** Currentpassword */
            currentPassword: string;
            /** Newpassword */
            newPassword: string;
        };
        /** ReadyzDependency */
        ReadyzDependency: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "skipped" | "error";
        };
        /** ReadyzResponse */
        ReadyzResponse: {
            /** Dependencies */
            dependencies: components["schemas"]["ReadyzDependency"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** RegisterEmailRequestV2 */
        RegisterEmailRequestV2: {
            /**
             * Displayname
             * @default New User
             */
            displayName: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RegisterPhoneRequestV2 */
        RegisterPhoneRequestV2: {
            /**
             * Displayname
             * @default New User
             */
            displayName: string;
            /** Password */
            password: string;
            /** Phone */
            phone: string;
            /** Smscode */
            smsCode: string;
        };
        /** ResetPasswordRequestV2 */
        ResetPasswordRequestV2: {
            /** Code */
            code: string;
            /** Identifier */
            identifier: string;
            /** Newpassword */
            newPassword: string;
        };
        /** ReviewAttemptOutV2 */
        ReviewAttemptOutV2: {
            /** Attemptedat */
            attemptedAt: string;
            /** Id */
            id: number;
            /** Outcome */
            outcome: string;
        };
        /** ReviewDetailResponseV2 */
        ReviewDetailResponseV2: {
            /** Actions */
            actions: components["schemas"]["ActionLinkV2"][];
            /** History */
            history: components["schemas"]["ReviewAttemptOutV2"][];
            item: components["schemas"]["ReviewItemV2"];
        };
        /** ReviewItemV2 */
        ReviewItemV2: {
            /** Createdat */
            createdAt: string;
            /** Href */
            href: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** ReviewListResponseV2 */
        ReviewListResponseV2: {
            /** Items */
            items: components["schemas"]["ReviewItemV2"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** SectionCardV2 */
        SectionCardV2: {
            /** Description */
            description: string;
            /** Href */
            href: string;
            /** Key */
            key: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** SendCodeRequestV2 */
        SendCodeRequestV2: {
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "register" | "reset_password" | "login" | "bind";
            /**
             * Targetkind
             * @enum {string}
             */
            targetKind: "email" | "phone";
            /** Targetvalue */
            targetValue: string;
        };
        /** SendCodeResponseV2 */
        SendCodeResponseV2: {
            /** Delivery */
            delivery: string;
            /** Ok */
            ok: boolean;
            /** Purpose */
            purpose: string;
        };
        /** SummaryMetricV2 */
        SummaryMetricV2: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
            /** Value */
            value: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyCodeRequestV2 */
        VerifyCodeRequestV2: {
            /** Code */
            code: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "register" | "reset_password" | "login" | "bind";
            /**
             * Targetkind
             * @enum {string}
             */
            targetKind: "email" | "phone";
            /** Targetvalue */
            targetValue: string;
        };
        /** VerifyCodeResponseV2 */
        VerifyCodeResponseV2: {
            /** Message */
            message: string;
            /** Verified */
            verified: boolean;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Appname */
            appName: string;
            /** Appversion */
            appVersion: string;
            /** Buildtime */
            buildTime: string;
            /** Env */
            env: string;
            /** Gitsha */
            gitSha: string;
            /** Imagetag */
            imageTag: string;
            /** Schemaversion */
            schemaVersion: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v2_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v2_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthAckV2"];
                };
            };
        };
    };
    register_email_api_v2_auth_register_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterEmailRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_phone_api_v2_auth_register_phone_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPhoneRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v2_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthAckV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_code_api_v2_auth_send_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCodeRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendCodeResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v2_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionStateResponseV2"];
                };
            };
        };
    };
    verify_code_api_v2_auth_verify_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCodeResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_overview_api_v2_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_progress_overview_api_v2_dashboard_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProgressResponseV2"];
                };
            };
        };
    };
    get_progress_diagnosis_api_v2_dashboard_progress_diagnosis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_progress_trend_api_v2_dashboard_progress_trend_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_progress_weakness_api_v2_dashboard_progress_weakness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_dashboard_records_api_v2_dashboard_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardRecordsResponseV2"];
                };
            };
        };
    };
    get_dashboard_today_api_v2_dashboard_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardTodayResponseV2"];
                };
            };
        };
    };
    get_dashboard_today_continue_api_v2_dashboard_today_continue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_dashboard_today_must_do_api_v2_dashboard_today_must_do_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_dashboard_today_review_api_v2_dashboard_today_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_dashboard_weekly_plan_api_v2_dashboard_weekly_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardWeeklyPlanResponseV2"];
                };
            };
        };
    };
    get_dashboard_weekly_adjust_api_v2_dashboard_weekly_plan_adjust_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_dashboard_weekly_goal_api_v2_dashboard_weekly_plan_goal_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    get_dashboard_weekly_completion_api_v2_dashboard_weekly_plan_today_completion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    list_notes_api_v2_notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteListResponseV2"];
                };
            };
        };
    };
    create_note_api_v2_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetailV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_api_v2_notes__note_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetailV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_v2_notes__note_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetailV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_center_api_v2_practice_center_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeCenterResponseV2"];
                };
            };
        };
    };
    list_essay_categories_api_v2_practice_essay_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogListResponseV2"];
                };
            };
        };
    };
    list_essay_papers_api_v2_practice_essay_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogListResponseV2"];
                };
            };
        };
    };
    create_session_api_v2_practice_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionCreateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionEnvelopeV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v2_practice_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionEnvelopeV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_answers_api_v2_practice_sessions__session_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeAnswerUpsertRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAckV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v2_practice_sessions__session_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResultResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_session_api_v2_practice_sessions__session_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAckV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_xingce_categories_api_v2_practice_xingce_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogListResponseV2"];
                };
            };
        };
    };
    list_xingce_papers_api_v2_practice_xingce_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogListResponseV2"];
                };
            };
        };
    };
    get_profile_goals_api_v2_profile_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGoalsResponseV2"];
                };
            };
        };
    };
    put_profile_goals_api_v2_profile_goals_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileGoalsUpdateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGoalsResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_info_api_v2_profile_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileInfoResponseV2"];
                };
            };
        };
    };
    put_profile_info_api_v2_profile_info_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInfoUpdateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileInfoResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_overview_api_v2_profile_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOverviewResponseV2"];
                };
            };
        };
    };
    get_profile_security_api_v2_profile_security_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSecurityResponseV2"];
                };
            };
        };
    };
    put_profile_security_api_v2_profile_security_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSecurityUpdateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSecurityResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_items_api_v2_review_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponseV2"];
                };
            };
        };
    };
    get_review_item_api_v2_review_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetailResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redo_review_item_api_v2_review_items__item_id__redo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAckV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_smart_review_api_v2_review_smart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseV2"];
                };
            };
        };
    };
    bootstrap_api_v2_system_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponseV2"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    version_json_version_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
